Global state edition
SELab-2/OSOC-6 pull request #363
Opened 2022-04-28 18:17 UTC by jitsedesmet

This PR aims to close #346.

2022-05-01 22:20 UTC, jitsedesmet commented
this PR introduces some latency when running with `npm run dev` (I think). The latency is acceptable when running in production though.

2022-05-02 18:29 UTC, andpuydt requested changes
Looks good, just a few questions. Since this PR will require a lot of changes on the ongoing branches, could you maybe add an overview of those changes? Such as the use of useSwrWithEdition, the path transformer, an explanation for the changed pathnames, etc. Could you also add some tests?

2022-05-02 18:29 UTC, andpuydt commented on frontend/src/components/routeInjector.tsx
> +            Router.replace({
Same as before concerning the Router.

2022-05-02 18:29 UTC, andpuydt commented on frontend/src/components/routeInjector.tsx
> +            Router.replace({
Same as before concerning the Router.

2022-05-03 06:45 UTC, jitsedesmet commented on frontend/src/api/calls/baseCalls.tsx
> +                cache[url] = (await getEntityOnUrl(url))!;
The type of getEntityOnUrl has changed to also be undefined.

2022-05-03 06:49 UTC, jitsedesmet commented on frontend/src/components/routeGuard.tsx
> +            Router.replace({
I think this triggerd the useEffect constantly but if you want I can verify this.

2022-05-03 06:50 UTC, jitsedesmet commented
> Looks good, just a few questions. Since this PR will require a lot of changes on the ongoing branches, could you maybe add an overview of those changes? Such as the use of useSwrWithEdition, the path transformer, an explanation for the changed pathnames, etc. Could you also add some tests?

What kind of tests are you thinking of? (Also not the urgency behind this PR)

2022-05-03 08:02 UTC, jitsedesmet commented on frontend/src/components/routeGuard.tsx
> +            Router.replace({
Hmm, seems like I was wrong. Thanks for pointing this out.

2022-05-03 08:25 UTC, jitsedesmet commented
This PR essentially introduces only 2 functions.
First we have  `useSwrWithEdition` this hook takes the same arguments as useSwr but will make sure the call is queried with the current edition id. The back end is written in a way that every search/by-edition expects the same argument edition so this function generalizes just that.

Second we have `useEditionPathTransformer` this hook returns a function that when provided with a front end path, return the same path but with the front end edition query. Whenever you route to a page that is edition dependent, you should use this transformer.

I hope this is clear. If not, please say so.

2022-05-04 08:34 UTC, andpuydt approved these changes

2022-05-04 08:35 UTC, andpuydt commented
> This PR essentially introduces only 2 functions. First we have `useSwrWithEdition` this hook takes the same arguments as useSwr but will make sure the call is queried with the current edition id. The back end is written in a way that every search/by-edition expects the same argument edition so this function generalizes just that.
> 
> Second we have `useEditionPathTransformer` this hook returns a function that when provided with a front end path, return the same path but with the front end edition query. Whenever you route to a page that is edition dependent, you should use this transformer.
> 
> I also implemented a `useOwnUser` hook. This hook just does what it says.
> 
> I hope this is clear. If not, please say so.

Can you pin this on discord for @ruvmello and @thvmulle so they are aware of the changes as well?

2022-05-04 09:18 UTC, merged